# pragma once

#include "../ast/astvisitor.h"
#include "../ast/Expression/ExprConstBlock.h"
#include "../ast/Expression/ExprStruct.h"
#include "../ast/Expression/expression.h"
#include "../ast/root.h"
#include "../ast/Expression/ExprArray.h"
#include "../ast/Expression/ExprBlock.h"
#include "../ast/Expression/ExprBreak.h"
#include "../ast/Expression/ExprCall.h"
#include "../ast/Expression/ExprContinue.h"
#include "../ast/Expression/ExprField.h"
#include "../ast/Expression/ExprGroup.h"
#include "../ast/Expression/ExprIf.h"
#include "../ast/Expression/ExprIndex.h"
#include "../ast/Expression/ExprLiteral.h"
#include "../ast/Expression/ExprLoop.h"
#include "../ast/Expression/ExprMatch.h"
#include "../ast/Expression/ExprMethodcall.h"
#include "../ast/Expression/ExprOpbinary.h"
#include "../ast/Expression/ExprOpunary.h"
#include "../ast/Expression/ExprPath.h"
#include "../ast/Expression/ExprReturn.h"
#include "../ast/Expression/ExprUnderscore.h"
#include "../ast/Item/ItemConst.h"
#include "../ast/Item/ItemEnum.h"
#include "../ast/Item/ItemFn.h"
#include "../ast/Item/ItemImpl.h"
#include "../ast/Item/ItemStruct.h"
#include "../ast/Item/ItemTrait.h"
#include "../ast/Pattern/PatternIdentifier.h"
#include "../ast/Pattern/PatternLiteral.h"
#include "../ast/Pattern/PatternPath.h"
#include "../ast/Pattern/PatternReference.h"
#include "../ast/Pattern/PatternTupleStruct.h"
#include "../ast/Pattern/PatternWildcard.h"
#include "../ast/Statement/StmtEmpty.h"
#include "../ast/Statement/StmtExpr.h"
#include "../ast/Statement/StmtItem.h"
#include "../ast/Statement/StmtLet.h"
#include "../ast/Type/type.h"
#include "../ast/Type/TypeArray.h"
#include "../ast/Type/TypePath.h"
#include "../ast/Type/TypeReference.h"
#include "../ast/Type/TypeUnit.h"
#include "globalScope.h"
#include "scope.h"
#include "symbol.h"
#include <iostream>
#include <memory>

// part generated by github copilot.
namespace JaneZ {
class NameResolver : public ASTVisitor{
public:
    std::shared_ptr<ScopeNode> current_scope;

    GlobalScopeBuilder global_scope_builder;

    NameResolver() = default;

    NameResolver(std::shared_ptr<ScopeNode> global_scope) : current_scope(std::move(global_scope)) {}

    ~NameResolver() = default;
    
    //Start: generated by github copilot.
    void visit(ASTNode &node) override {
        if(auto *p = dynamic_cast<ASTRootNode *>(& node)) {
            node.accept(*this);
        }else if(auto *p = dynamic_cast<Expression *>(& node)) {
            node.accept(*this);
        }else if(auto *p = dynamic_cast<Item *>(& node)) {
            node.accept(*this);
        }else if(auto *p = dynamic_cast<Pattern *>(& node)) {
            node.accept(*this);
        }else if(auto *p = dynamic_cast<Statement *>(& node)) {
            node.accept(*this);
        }else if(auto *p = dynamic_cast<Type *>(& node)) {
            node.accept(*this);
        }else if(auto *p = dynamic_cast<TypeArray *>(& node)) {
            node.accept(*this);
        }else if(auto *p = dynamic_cast<TypePath *>(& node)) {
            node.accept(*this);
        }else if(auto *p = dynamic_cast<TypeReference *>(& node)) {
            node.accept(*this);
        }else if(auto *p = dynamic_cast<TypeUnit *>(& node)) {
            node.accept(*this);
        }else{
            std::cout << "Unknown node type in PrintVisitor\n";
        }
    }
    //End: generated by github copilot.

    void visit(ASTRootNode &node) override {
        for(auto &item : node.child) {
            //item->accept(*this);
            visit(*item);
        }
    }

    //Expression
    void visit(Expression &node) override {
        if(auto *p = dynamic_cast<ExprArray *>(& node)) {
            p->accept(*this);
        }else if(auto *p = dynamic_cast<ExprBlock *>(& node)) {
            p->accept(*this);
        }else if(auto *p = dynamic_cast<ExprBreak *>(& node)) {
            p->accept(*this);
        }else if(auto *p = dynamic_cast<ExprCall *>(& node)) {
            p->accept(*this);
        }else if(auto *p = dynamic_cast<ExprConstBlock *>(& node)) {
            p->accept(*this);
        }else if(auto *p = dynamic_cast<ExprContinue *>(& node)) {
            p->accept(*this);
        }else if(auto *p = dynamic_cast<ExprField *>(& node)) {
            p->accept(*this);
        }else if(auto *p = dynamic_cast<ExprGroup *>(& node)) {
            p->accept(*this);
        }else if(auto *p = dynamic_cast<ExprIf *>(& node)) {
            p->accept(*this);
        }else if(auto *p = dynamic_cast<ExprIndex *>(& node)) {
            p->accept(*this);
        }else if(auto *p = dynamic_cast<ExprLiteral *>(& node)) {
            p->accept(*this);
        }else if(auto *p = dynamic_cast<ExprLoop *>(& node)) {
            p->accept(*this);
        }else if(auto *p = dynamic_cast<ExprMatch *>(& node)) {
            p->accept(*this);
        }else if(auto *p = dynamic_cast<ExprMethodcall *>(& node)) {
            p->accept(*this);
        }else if(auto *p = dynamic_cast<ExprOpbinary *>(& node)) {
            p->accept(*this);
        }else if(auto *p = dynamic_cast<ExprOpunary *>(& node)) {
            p->accept(*this);
        }else if(auto *p = dynamic_cast<ExprPath *>(& node)) {
            p->accept(*this);
        }else if(auto *p = dynamic_cast<ExprReturn *>(& node)) {
            p->accept(*this);
        }else if(auto *p = dynamic_cast<ExprStruct *>(& node)) {
            p->accept(*this);
        }else if(auto *p = dynamic_cast<ExprUnderscore *>(& node)) {
            p->accept(*this);
        }else{
            std::cout << "Unknown Expression type in PrintVisitor\n";
        }
    }

    void visit(ExprArray &node) override{
        if(node.arrayExpr.size() > 0) {
            for(auto &expr : node.arrayExpr) {
                expr->accept(*this);
            }
        }else{
            node.size->accept(*this);
            node.type->accept(*this);
        }
    }

    void visit(ExprBlock &node) override{
        if(node.statements.size() > 0){
            for(auto &stmt : node.statements) {
                stmt->accept(*this);
            }
        }
        if(node.ExpressionWithoutBlock){
            node.ExpressionWithoutBlock->accept(*this);
        }
    }

    void visit(ExprBreak &node) override{}

    void visit(ExprCall &node) override{
        node.expr->accept(*this);
        if(node.callParams.size() > 0) {
            for(auto &param : node.callParams) {
                param->accept(*this);
            }
        }
    }

    void visit(ExprConstBlock &node) override{
        node.expr->accept(*this);
    }

    void visit(ExprContinue &node) override{}

    void visit(ExprField &node) override{
        node.expr->accept(*this);
    }

    void visit(ExprGroup &node) override{
        node.expr->accept(*this);
    }

    void visit(ExprIf &node) override{
        node.condition->accept(*this);
        node.thenBlock->accept(*this);
        if(node.elseBlock){
            node.elseBlock->accept(*this);
        }
    }

    void visit(ExprIndex &node) override{
        node.name->accept(*this);
        node.index->accept(*this);
    }

    void visit(ExprLiteral &node) override{}

    void visit(ExprLoop &node) override{
        if(node.infinitieLoop){
            node.infinitieLoop->accept(*this);
        }else{
            if(node.condition){
                node.condition->accept(*this);
            }
            if(node.PredicateLoopExpression){
                node.PredicateLoopExpression->accept(*this);
            }
        }
    }

    void visit(ExprMethodcall &node) override{
        node.expr->accept(*this);
        node.PathExprSegment->accept(*this);
        if(node.callParams.size() > 0) {
            for(auto &param : node.callParams) {
                param->accept(*this);
            }
        }
    }

    void visit(ExprOpbinary &node) override{
        node.left->accept(*this);
        node.right->accept(*this);
    }

    void visit(ExprOpunary &node) override{
        node.right->accept(*this);
    }

    void visit(ExprPath &node) override{
        node.pathFirst->accept(*this);
        if(node.pathSecond){
            node.pathSecond->accept(*this);
            if(node.pathFirst->pathSegments.type == IDENTIFIER) {
                auto symbol = current_scope->lookupTypeSymbol(node.pathFirst->pathSegments.identifier);
                if(!symbol) {
                    throw std::runtime_error("Type symbol not found: " + node.pathFirst->pathSegments.identifier);
                }else{
                    node.resolvedSymbol1 = symbol;
                }
            }
            if(node.pathSecond->pathSegments.type == IDENTIFIER) {
                auto symbol2 = current_scope->lookupValueSymbol(node.pathSecond->pathSegments.identifier);
                if(!symbol2) {
                    throw std::runtime_error("Value symbol not found: " + node.pathSecond->pathSegments.identifier);
                }else{
                    node.resolvedSymbol2 = symbol2;
                }
            }
        }else{
            if(node.pathFirst->pathSegments.type == IDENTIFIER) {
                auto symbol = current_scope->lookupValueSymbol(node.pathFirst->pathSegments.identifier);
                if(!symbol) {
                    symbol = current_scope->lookupTypeSymbol(node.pathFirst->pathSegments.identifier);
                    if(!symbol) {
                        throw std::runtime_error("Symbol not found: " + node.pathFirst->pathSegments.identifier);
                    }else{
                        node.resolvedSymbol1 = symbol;
                    }
                }else{
                    node.resolvedSymbol1 = symbol;
                }
            }
        }
    }

    void visit(ExprReturn &node) override{
        if(node.expr){
            node.expr->accept(*this);
        }
    }

    void visit(ExprStruct &node) override{
        node.pathInExpr->accept(*this);
        for(auto &field : node.structExprFields) {
            std::cout << field.identifier << ": ";
            field.expr->accept(*this);
        }
    }

    void visit(ExprUnderscore &node) override{}

    //Item
    void visit(Item &node) override {
        if(auto *p = dynamic_cast<ItemConstDecl *>(& node)) {
            p->accept(*this);
        }else if(auto *p = dynamic_cast<ItemEnumDecl *>(& node)) {
            p->accept(*this);
        }else if(auto *p = dynamic_cast<ItemFnDecl *>(& node)) {
            p->accept(*this);
        }else if(auto *p = dynamic_cast<ItemImplDecl *>(& node)) {
            p->accept(*this);
        }else if(auto *p = dynamic_cast<ItemStructDecl *>(& node)) {    
            p->accept(*this);
        }else if(auto *p = dynamic_cast<ItemTraitDecl *>(& node)) {
            p->accept(*this);
        }else{
            std::cerr << "Unknown Item type in NameResolver\n";
        }
    }

    void visit(ItemConstDecl &node) override{
        if(current_scope != global_scope_builder.global_scope){
            current_scope->addValueSymbol(node.identifier, std::make_shared<Symbol>(std::make_shared<ItemConstDecl>(node), Const, node.identifier));
        }
        //current_scope->addValueSymbol(node.identifier, std::make_shared<Symbol>(std::make_shared<ItemConstDecl>(node), Const, node.identifier));
        node.type->accept(*this);
        if(auto *p = dynamic_cast<TypePath *>(& *node.type)) {
            std::string id = p->typePath->pathSegments.identifier;
            auto symbol = current_scope->lookupTypeSymbol(id);
            if(!symbol) {
                throw std::runtime_error("Value symbol not found: " + id);
            }else{
                p->resolvedSymbol = symbol;
            }
        }
        if(node.expr){
            node.expr->accept(*this);
        }
    }

    void visit(ItemEnumDecl &node) override{
        if(current_scope != global_scope_builder.global_scope){
            current_scope->addTypeSymbol(node.identifier, std::make_shared<Symbol>(std::make_shared<ItemEnumDecl>(node), Enum, node.identifier));
        }
        for(auto &variant : node.item_enum) {
            current_scope->addValueSymbol(variant, std::make_shared<Symbol>(std::make_shared<ItemEnumDecl>(node), Enum, variant));
        }
    }

    void visit(ItemFnDecl &node) override{
        if(current_scope != global_scope_builder.global_scope){
            current_scope->addValueSymbol(node.identifier, std::make_shared<Symbol>(std::make_shared<ItemFnDecl>(node), Function, node.identifier));
        }
        //current_scope->addValueSymbol(node.identifier, std::make_shared<Symbol>(std::make_shared<ItemFnDecl>(node), Function, node.identifier));
        auto fn_scope = std::make_shared<ScopeNode>();
        fn_scope->parent = current_scope;
        fn_scope->ast_node = std::make_shared<ItemFnDecl>(node);
        current_scope = fn_scope;
        for(auto &param: node.fnParameters.FunctionParam){
            if(auto *p = dynamic_cast<PatternIdentifier *>(& *param.pattern)){
                if(auto *r = dynamic_cast<Type *>(& *param.type)){
                    current_scope->addValueSymbol(p->identifier, std::make_shared<Symbol>(std::make_shared<Type>(*r), Variable, p->identifier));
                }else if(auto *r = dynamic_cast<TypeReference *>(& *param.type)){
                    current_scope->addValueSymbol(p->identifier, std::make_shared<Symbol>(std::make_shared<TypeReference>(*r), Variable, p->identifier));
                }else if(auto *r = dynamic_cast<TypePath *>(& *param.type)){
                    current_scope->addValueSymbol(p->identifier, std::make_shared<Symbol>(std::make_shared<TypePath>(*r), Variable, p->identifier));
                }else if(auto *r = dynamic_cast<TypeArray *>(& *param.type)){   
                    current_scope->addValueSymbol(p->identifier, std::make_shared<Symbol>(std::make_shared<TypeArray>(*r), Variable, p->identifier));
                }else if(auto *r = dynamic_cast<TypeUnit *>(& *param.type)){
                    current_scope->addValueSymbol(p->identifier, std::make_shared<Symbol>(std::make_shared<TypeUnit>(*r), Variable, p->identifier));
                }
            }else if(auto *p = dynamic_cast<PatternReference *>(& *param.pattern)){
                if(auto *q = dynamic_cast<PatternIdentifier *>(& *p->patternWithoutRange)){
                    if(auto *r = dynamic_cast<Type *>(& *param.type)){
                        current_scope->addValueSymbol(q->identifier, std::make_shared<Symbol>(std::make_shared<Type>(*r), Variable, q->identifier));
                    }else if(auto *r = dynamic_cast<TypeReference *>(& *param.type)){
                        current_scope->addValueSymbol(q->identifier, std::make_shared<Symbol>(std::make_shared<TypeReference>(*r), Variable, q->identifier));
                    }else if(auto *r = dynamic_cast<TypePath *>(& *param.type)){
                        current_scope->addValueSymbol(q->identifier, std::make_shared<Symbol>(std::make_shared<TypePath>(*r), Variable, q->identifier));
                    }else if(auto *r = dynamic_cast<TypeArray *>(& *param.type)){   
                        current_scope->addValueSymbol(q->identifier, std::make_shared<Symbol>(std::make_shared<TypeArray>(*r), Variable, q->identifier));
                    }else if(auto *r = dynamic_cast<TypeUnit *>(& *param.type)){
                        current_scope->addValueSymbol(q->identifier, std::make_shared<Symbol>(std::make_shared<TypeUnit>(*r), Variable, q->identifier));
                    }
                }
            }
            if(auto *p = dynamic_cast<TypePath *>(& *param.type)){
                std::string id = p->typePath->pathSegments.identifier;
                auto symbol = current_scope->lookupTypeSymbol(id);
                if(!symbol) {
                    throw std::runtime_error("Value symbol not found: " + id);
                }else{
                    p->resolvedSymbol = symbol;
                }
            }
        }
        if(node.returnType){
            if(auto *p = dynamic_cast<TypePath *>(& *node.returnType)){
                std::string id = p->typePath->pathSegments.identifier;
                auto symbol = current_scope->lookupTypeSymbol(id);
                if(!symbol) {
                    throw std::runtime_error("Value symbol not found: " + id);
                }else{
                    p->resolvedSymbol = symbol;
                }
            }
        }
        if(node.fnBody){
            node.fnBody->accept(*this);
        }
        current_scope = current_scope->parent;
    }

    void visit(ItemImplDecl &node) override{
        if(node.identifier != ""){
            auto symbolTYPE = current_scope->lookupTypeSymbol(node.identifier);
            if(!symbolTYPE) {
                throw std::runtime_error("Type symbol not found: " + node.identifier);
            }
            if(auto *p = dynamic_cast<TypePath *>(& *node.targetType)){
                std::string id = p->typePath->pathSegments.identifier;
                auto symbolTYPE = current_scope->lookupTypeSymbol(id);
                if(!symbolTYPE) {
                    throw std::runtime_error("Type symbol not found: " + id);
                }else{
                    p->resolvedSymbol = symbolTYPE;
                }
            }
            for(auto &const_item : node.item_trait_const) {
                const_item->accept(*this);
            }
            for(auto &fn_item : node.item_trait_fn) {
                fn_item->accept(*this); 
            }
        }else{
            if(auto *p = dynamic_cast<TypePath *>(& *node.targetType)){
                std::string id = p->typePath->pathSegments.identifier;
                auto symbolTYPE = current_scope->lookupTypeSymbol(id);
                if(!symbolTYPE) {
                    throw std::runtime_error("Type symbol not found: " + id);
                }else{
                    p->resolvedSymbol = symbolTYPE;
                }
            }
            for(auto &const_item : node.item_trait_const) {
                const_item->accept(*this);  
            }
            for(auto &fn_item : node.item_trait_fn) {
                fn_item->accept(*this); 
            }
        }
    }

    void visit(ItemStructDecl &node) override{
        if(current_scope != global_scope_builder.global_scope){
            current_scope->addTypeSymbol(node.identifier, std::make_shared<Symbol>(std::make_shared<ItemStructDecl>(node), Struct, node.identifier));
        }
        //current_scope->addTypeSymbol(node.identifier, std::make_shared<Symbol>(std::make_shared<ItemStructDecl>(node), Struct, node.identifier));
        for(auto &struct_field: node.item_struct) {
            if(auto *p = dynamic_cast<TypePath *>(& *struct_field.structElem)){
                std::string id = p->typePath->pathSegments.identifier;
                auto symbol = current_scope->lookupTypeSymbol(id);
                if(!symbol) {
                    throw std::runtime_error("Value symbol not found: " + id);
                }else{
                    p->resolvedSymbol = symbol;
                }
            }
            current_scope->addValueSymbol(struct_field.identifier, std::make_shared<Symbol>(std::make_shared<ItemStructDecl>(node), Variable, struct_field.identifier));
        }
    }

    void visit(ItemTraitDecl &node) override{
        if(current_scope != global_scope_builder.global_scope){
            current_scope->addTypeSymbol(node.identifier, std::make_shared<Symbol>(std::make_shared<ItemTraitDecl>(node), Trait, node.identifier));
        }
        //current_scope->addTypeSymbol(node.identifier, std::make_shared<Symbol>(std::make_shared<ItemTraitDecl>(node), Trait, node.identifier));
        for(auto &const_item : node.item_trait_const) {
            const_item->accept(*this);  
        }
        for(auto &fn_item : node.item_trait_fn) {
            fn_item->accept(*this); 
        }
    }

    //Pattern
    void visit(Pattern &node) override {
        if(auto *p = dynamic_cast<PatternIdentifier *>(& node)) {
            p->accept(*this);
        }else if(auto *p = dynamic_cast<PatternLiteral *>(& node)) {
            p->accept(*this);
        }else if(auto *p = dynamic_cast<PatternPath *>(& node)) {
            p->accept(*this);     
        }else if(auto *p = dynamic_cast<PatternReference *>(& node)) {
            p->accept(*this);
        }else if(auto *p = dynamic_cast<PatternWildCard *>(& node)) {   
            p->accept(*this);
        }else if(auto *p = dynamic_cast<PatternTupleStruct *>(& node)) {
            p->accept(*this);
        }else{
            std::cout << "Unknown Pattern type in PrintVisitor\n";
        }
    }

    void visit(PatternIdentifier &node) override{}

    void visit(PatternLiteral &node) override{}

    void visit(PatternPath &node) override{}

    void visit(PatternReference &node) override{}

    void visit(PatternWildCard &node) override{}

    //Statement
    void visit(Statement &node) override {
        if(auto *p = dynamic_cast<StmtEmpty *>(& node)) {
            p->accept(*this);
        }else if(auto *p = dynamic_cast<StmtExpr *>(& node)) {
            p->accept(*this);
        }else if(auto *p = dynamic_cast<StmtItem *>(& node)) {
            p->accept(*this);
        }else if(auto *p = dynamic_cast<StmtLet *>(& node)) {
            p->accept(*this);
        }else{
            std::cout << "Unknown Statement type in PrintVisitor\n";
        }
    }

    void visit(StmtEmpty &node) override{}

    void visit(StmtExpr &node) override{
        node.stmtExpr->accept(*this);
    }

    void visit(StmtItem &node) override{
        node.stmt_item->accept(*this);
    }

    void visit(StmtLet &node) override{
        if(auto *p = dynamic_cast<PatternIdentifier *>(& *node.PatternNoTopAlt)){
            current_scope->addValueSymbol(p->identifier, std::make_shared<Symbol>(std::make_shared<StmtLet>(node), Variable, p->identifier));
        }else if(auto *p = dynamic_cast<PatternReference *>(& *node.PatternNoTopAlt)){
            if(auto *q = dynamic_cast<PatternIdentifier *>(& *p->patternWithoutRange)){
                current_scope->addValueSymbol(q->identifier, std::make_shared<Symbol>(std::make_shared<StmtLet>(node), Variable, q->identifier));
            }
        }
        if(auto *p = dynamic_cast<TypePath *>(& *node.type)){
            std::string id = p->typePath->pathSegments.identifier;
            auto symbol = current_scope->lookupTypeSymbol(id);
            if(!symbol) {
                throw std::runtime_error("Value symbol not found: " + id);
            }else{
                p->resolvedSymbol = symbol;
            }
        }
        node.expression->accept(*this);
    }


    //Type
    void visit(Type &node) override {}

    void visit(TypeArray &node) override{}
    
    void visit(TypePath &node) override{}

    void visit(TypeReference &node) override{}

    void visit(TypeUnit &node) override{}

    //Path
    void visit(Path &node) override{}
};
}