# pragma once

#include "item.h"
#include <memory>
#include <vector>
namespace JaneZ {
class ItemStructDecl : public Item {
private:
    std::string identifier;
    std::vector<std::unique_ptr<ItemStructVariant>> item_struct;
public:
    //Start generated by Copilot.
    ItemStructDecl(std::string _identifier, 
                    std::vector<std::unique_ptr<ItemStructVariant>> _item_struct) 
        : identifier(std::move(_identifier)), item_struct(std::move(_item_struct)) {}
    //End generated by Copilot.

    ~ItemStructDecl() = default;

    void accept(ASTVisitor &visitor) override {
        visitor.visit(*this);
    }
};
}