# pragma once

#include "item.h"
#include <vector>
namespace JaneZ {
class ItemStructDecl : public Item {
public:
    std::string identifier;
    std::vector<ItemStructVariant> item_struct;

    //Start generated by Copilot.
    ItemStructDecl(std::string _identifier, 
                    std::vector<ItemStructVariant> _item_struct) 
        : identifier(std::move(_identifier)), item_struct(std::move(_item_struct)) {}
    //End generated by Copilot.

    ~ItemStructDecl() = default;

    void accept(ASTVisitor &visitor) override {
        visitor.visit(*this);
    }
};
}